### ISSUE TITLE
getting a lot of dependency issues with "npm install"

### ISSUE THREAD

**Issue by SteveALee** [kahlil/cycle-browserify-boilerplate#3]
I tried updating deps to latest but then got issues

For example the cycle eslint config wants eslint 1.x.x. I see you updated the code but doesn't seem to be in npm  :( 

had to add "eslint-plugin-no-class"

cyclic-history wants the old history 1.17.0 the latest 2.0.1 breaks this and the install

gracefull-fs  < 4.0.0 is depreciated several deps for this

lodash 2.1.0 is depreciated

**Comment by SteveALee** [comment]
I;m using node 4.3.2 and npm 2.14.12

**Comment by khalillechelt** [comment]
Hey thanks man the app still works for you though right?
I will look into this, talk to @Cmdv and @staltz to see that we can get deprecations out.

**Comment by SteveALee** [comment]
> Hey thanks man the app still works for you though right?

Once  I removed the explicit dependencies on ESlint 2.x.x and history 2.x,x then it all worked. I also cleared my npm chaces for good measure. I was surprised I had that tissue pre npm 3. I obviously don't full understand the deps. :)

I tried in Microsoft Edge first but it failed to connect to the server. Chrome worked just fine though. Strange.

**Comment by SteveALee** [comment]
> I will look into this, talk to @Cmdv and @staltz to see that we can get deprecations out.

Thanks. It would be good as seems like a great boiler plate. If a little more comprehensive than I initially need.

Is there a way to proxy through live server to project HTML /  API server?

**Comment by SteveALee** [comment]
Also need estraverse-fb for babel lint - seems to be a [known issue](https://github.com/eslint/eslint/issues/5476)

**Comment by SteveALee** [comment]
PS looks like lint was not run before last commit :) Loads of errors

**Comment by khalillechelt** [comment]
:) thanks man! I'll get back on that soon :)

**Comment by SteveALee** [comment]
cheers, no rush - mostly line length > 80.
I had config problem causing more errors than I should have.

in the end I copy the cycle eslint config across so coule use eslint s.x.x. That just leaves no-class using crappy old version

**Comment by Cmdv** [comment]
@SteveALee I'm pretty sure I built the boilerplate with **Node v5.x** so you might have issues with **npm** complaining a lot.

try install [NVM](http://stackoverflow.com/questions/28017374/what-is-the-suggested-way-to-install-brew-node-js-io-js-nvm-npm-on-os-x) so you can easily chose the node version you require :+1:

If you're still having issues give us a shout

**Comment by SteveALee** [comment]
@Cmdv So far it's OK now with LTS apart from those deps issues. At least it runs and I can see timers counting and navigate

I have nvm so might try later. Having got it installed and running I'm now building up my project form minimal but adding bits from the boilerplate as I need.

I'm going to try cycle-history rather than cyclic but not sure what is better.

**Comment by SteveALee** [comment]
@Cmdv is this a different boilerplate to the one you have in mind?

**Comment by Cmdv** [comment]
@SteveALee check in the commit history as I had the boilerplate working with cycle-history. might have to just grab that out and over ride the current version.

> is this a different boilerplate to the one you have in mind?

these should be similar as it will have the history of mine before @kahlil converted it to his needs :)

**Comment by SteveALee** [comment]
@Cmdv ahah. Cheekily not forked :) joking

**Comment by Cmdv** [comment]
@SteveALee no it's fine it was agreed :wink:

**Comment by SteveALee** [comment]
@Cmdv Oh yes, I see your checkins. I'll do a bit of time travelling :)

**Comment by khalillechelt** [comment]
@staltz could you publish the latest version of eslint-plugin-cycle to npm so we have the eslint 2.x.x. peerDependency in there?

**Comment by khalillechelt** [comment]
I rolled back the eslint dep to 1.x.x because of https://github.com/cyclejs/eslint-config-cycle/issues/3#issuecomment-189608732

Closing this.

**Comment by staltz** [comment]
Hi @kahlil, sorry to be so late in participating in everything (you should see my github notification list), but I don't intend to maintain eslint-plugin-cycle anymore, because this was only used for Cycle.js libraries, not intended to be used for the general public. Since we are rewriting everything in Cycle.js to TypeScript, ESLint won't be used anymore and we will drop that repo.

We may later try to introduce a "standard Cycle.js code style", but not yet. I think a good place where these code style configs can live are either in boilerplates like your own (it can just specify the ~same rules that eslint-plugin-cycle does) or in generators like yeoman or something like Ember CLI.

**Comment by khalillechelt** [comment]
> Hi @kahlil, sorry to be so late in participating in everything (you should see my github notification list), 

:smile: no worries! I can imagine...

> We may later try to introduce a "standard Cycle.js code style", but not yet. I think a good place where these code style configs can live are either in boilerplates like your own (it can just specify the ~same rules that eslint-plugin-cycle does) or in generators like yeoman or something like Ember CLI.

OK. For now I am going to keep using eslint-config-cycle. It is a nice coding style. But I was wondering if we should maybe move to https://github.com/feross/standard for Cycle apps then it is a great little community project and is similar in its coding style.

Or do you recommend moving to TypeScript for apps as well?

**Comment by Cmdv** [comment]
TypeScript will just be for the API stuff because of its static typing and other advantages. I wouldn't worry about Cyle apps being made out of TypeScript as a requirement :)

**Comment by khalillechelt** [comment]
@Cmdv thanks! Got it. How do we feel about  https://github.com/feross/standard as a code style?

**Comment by Cmdv** [comment]
Looks like a reasonable standard to me, not looked at the plugin @staltz made so not sure what was put into that. Seems like it has all we normally use because at work we're on [airbnb](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) but that wan't the semi-colons and all the other annoying bits!

I'm easy either way all my code setting are in my IDE :stuck_out_tongue_closed_eyes:, bless you Intellij IDEA

**Comment by khalillechelt** [comment]
Kewl, so far I am not getting any bad vibes for Standard :) Playing with the thought of putting that in instead of eslint-config-cycle.

**Comment by SteveALee** [comment]
> Or do you recommend moving to TypeScript for apps as well?

Well, my long term plan is to move over to it. It has benefits for small projects as well as large projects where it really helps. I nearly switched after seeing Mobxjs is also using it, but one thing at a time. If you use MS Visual Studio dev tools like Code then the intellisense is fantastic with the new JS / TS language support. It also gives easy ES2015 support with less tooling (ie no need for babel).

For now the biggest downside I see is lack of ESLint support with TSLint being much less flexible or standard. Though ESLint is apparently working on TS support. I assume source maps are OK

**Comment by SteveALee** [comment]
> Kewl, so far I am not getting any bad vibes for Standard :

Yeah I was going to say you should just go for what you want to. Trying to get wider adoption is going to guarantee extreme bike shedding :) Semicolons and const for starters. And then the boilerplate's use of browserify/webpack, grunt/gulp/npm ......... life is too short (though I just switched back to webpack - hehe)

**Comment by SteveALee** [comment]
Having used standard now I find it good but a little cramped at times as it disallows whitespace where I would rather have it. Otherwise it's fine

**Comment by khalillechelt** [comment]
I am currently also eyeing XO https://github.com/sindresorhus/xo seems nice as well.

**Comment by khalillechelt** [comment]
Since this task is closed I am continuing the ruminatings on finding a good linting standard for this project over here: https://github.com/kahlil/cycle-browserify-boilerplate/issues/4
