### ISSUE TITLE
Introduce new (community driven) linting / code style

### ISSUE THREAD

**Issue by khalillechelt** [kahlil/cycle-browserify-boilerplate#4]
Since eslint-config-cycle and eslint-plugin-cycle are both deprecated because the lib is moving to TypeScript I am looking into 
- [Standard](https://github.com/feross/standard) and
- [XO](https://github.com/sindresorhus/xo) 

for linting. 

What I like about them is that they are community driven efforts to introduce sane code conventions into your code.

So far I am leaning towards XO. I think it's defaults are closer to a style that a majority of JS devs use than standard. On top of that it is easily customizable in the package.json which Standard is prohibiting.
Unfortunately I think reasons for customization can be manyfold though. So I like XO's approach better.

**Comment by SteveALee** [comment]
It also has plugins for various tools which is important. Plus being based on ESLint is a plus.

I'm unhappy with Standard too

**Comment by khalillechelt** [comment]
> It also has plugins for various tools which is important. 

True.

> Plus being based on ESLint is a plus.

Standard is based on ESLint as well.

**Comment by khalillechelt** [comment]
OK I integrated linting via [XO](https://github.com/sindresorhus/xo) + some really light customization (see the [package.json](https://github.com/kahlil/cycle-browserify-boilerplate/blob/master/package.json#L25-L33)) to fit the eslint-config-cycle style (which I quite enjoy). 

@staltz maybe you want to have a look at this as well for consideration of a community wide recommendation. I am quite happy with this. XO is quite a delight to use. @sindresorhus stuff mostly is :smile:

**Comment by SteveALee** [comment]
I've used much the same in my [package.json](https://github.com/OpenDirective/brian/blob/master/package.json#L70-L82)

You also want to turn off the [new-cap](http://eslint.org/docs/rules/new-cap) rule as Caps are used for cyclejs components [by convention](http://cycle.js.org/components.html#why-name-components-with-capitalcase).

However in VS Code I cannot get it to turn off :( SEE sindresorhus/xo#86

I also have server and frontend in same repo so might be a pain having common rules in package.json. But can at least define the env on the command line. I'll prolly split the code up anyway.

**Comment by SteveALee** [comment]
> You also want to turn off the new-cap rule as Caps are used for cyclejs components by convention.
> 
> However in VS Code I cannot get it to turn off :( SEE sindresorhus/xo#86

Use "babel/new-cap": 0

**Comment by khalillechelt** [comment]
> Use "babel/new-cap": 0

Thanks! Done.

**Comment by staltz** [comment]
@kahlil XO looks good :)

**Comment by khalillechelt** [comment]
:) yeah I like it

**Comment by SteveALee** [comment]
So far do good. Only glitch I have found is with layout of nested hyperscript. Works OK in VS Code too.

**Comment by khalillechelt** [comment]
@SteveALee that would be an ESLint glitch then I guess?

**Comment by SteveALee** [comment]
@kahlil I would think so. Requires time to explore options and tweak.

**Comment by SteveALee** [comment]
Fancy giving this a spin? Obviously not for drivers

https://github.com/jhusain/eslint-plugin-immutable/blob/master/README.md

**Comment by khalillechelt** [comment]
I would love to but why did he not publish this on npm? https://github.com/jhusain/eslint-plugin-immutable/issues/1

Seems weird.

**Comment by SteveALee** [comment]
Agree. In fact I assumed it was. You could raise a bug.

**Comment by khalillechelt** [comment]
3 people already did. He does not seem to care. Still the README says to install it via npm. Maybe I'll just "steal it" and publish it myself :smile:

**Comment by SteveALee** [comment]
Well it's, Apache 2.0 so that's fine. :)

Sent from Outlook Mobile

On Thu, Mar 17, 2016 at 7:52 AM -0700, "Kahlil Lechelt" notifications@github.com wrote:

3 people already did. He does not seem to care. Still the README says to install it via npm. Maybe I'll just "steal it" and publish it myself

**Comment by khalillechelt** [comment]
:)

**Comment by khalillechelt** [comment]
Trying it one last time: https://github.com/jhusain/eslint-plugin-immutable/issues/1#issuecomment-197921670

**Comment by SteveALee** [comment]
Those Netflix guys! I guess you could do and let him take over. Sort of contribution. But isn't it just s simple publish?

**Comment by khalillechelt** [comment]
Somebody published it already.

**Comment by SteveALee** [comment]
> Somebody published it already.

Today? Got a link?

**Comment by khalillechelt** [comment]
http://npm.im/eslint-plugin-immutable

**Comment by SteveALee** [comment]
> http://npm.im/eslint-plugin-immutable <
> http://npm.im/eslint-plugin-immutable>

er, that figures. </blush>

**Comment by khalillechelt** [comment]
I added the immutable plugin to this boilerplate as well. At first I was hesitant because the Atom linter plugin for xo did not work correctly. That is now fixed via a bugfix in eslint. See https://github.com/sindresorhus/atom-linter-xo/issues/19#issuecomment-202821782. 

I am closing this because linting in this boilerplate is NICE now 💅
